package com.yuegang.zhihui.search.application;
import com.yuegang.zhihui.common.core.*;import com.yuegang.zhihui.search.api.*;import com.yuegang.zhihui.search.infrastructure.*;import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.web.client.RestClient;
public final class HybridSearchService{
 private final JdbcTemplate jdbc;private final RestClient elastic;private final DoubaoEmbeddingGateway embeddings;private final String alias;
 public HybridSearchService(JdbcTemplate jdbc,String elasticBase,DoubaoEmbeddingGateway embeddings,String alias){this(jdbc,elasticBase,"","",embeddings,alias);}public HybridSearchService(JdbcTemplate jdbc,String elasticBase,String username,String password,DoubaoEmbeddingGateway embeddings,String alias){this.jdbc=jdbc;elastic=ElasticsearchRestClientFactory.create(elasticBase,username,password);this.embeddings=embeddings;this.alias=alias;}
 public List<SearchHit>search(SearchRequest request){List<Double>vector=embeddings.embed(request.query());String literal=vector.toString();var vectorHits=jdbc.query("SELECT document_id,chunk_id,document_version,source_updated_at,1-(embedding <=> ?::vector) score FROM search_embedding WHERE index_version=(SELECT active_version FROM search_index_version WHERE alias_name=?) ORDER BY embedding <=> ?::vector LIMIT ?",(row,n)->new Raw(row.getString(1),row.getString(2),"","",row.getLong(3),offset(row.getObject(4)),0,row.getDouble(5)),literal,alias,literal,request.limit()*2);Map<?,?>body=elastic.post().uri("/"+alias+"/_search").body(Map.of("size",request.limit()*2,"query",Map.of("bool",Map.of("must",List.of(Map.of("multi_match",Map.of("query",request.query(),"fields",List.of("title^3","content")))),"filter",request.category()==null?List.of():List.of(Map.of("term",Map.of("category",request.category()))))))).retrieve().body(Map.class);var lexical=parse(body);var merged=new LinkedHashMap<String,Raw>();int rank=1;for(var hit:lexical){double rrf=1d/(60+rank++);merged.put(hit.key(),hit.withLexical(rrf));}rank=1;for(var hit:vectorHits){double rrf=1d/(60+rank++);merged.merge(hit.key(),hit.withVector(rrf),Raw::merge);}return merged.values().stream().sorted(Comparator.comparingDouble(Raw::finalScore).reversed()).limit(request.limit()).map(x->new SearchHit(x.document,x.chunk,x.title,excerpt(x.content),x.documentVersion,x.updatedAt,x.lexical,x.vector,x.finalScore())).toList();}
 public void index(IndexChunkCommand command){if(!command.published())throw new BusinessException(ErrorCode.PERMISSION_DENIED);var vector=embeddings.embed(command.content());jdbc.update("INSERT INTO search_embedding(document_id,chunk_id,index_version,visibility,embedding,content_sha256,document_version,source_updated_at) VALUES(?,?,?,?,?::vector,encode(sha256(?::bytea),'hex'),?,?) ON CONFLICT(document_id,chunk_id,index_version) DO UPDATE SET embedding=EXCLUDED.embedding,visibility=EXCLUDED.visibility,document_version=EXCLUDED.document_version,source_updated_at=EXCLUDED.source_updated_at",Long.parseLong(command.documentId()),Long.parseLong(command.chunkId()),command.indexVersion(),command.visibility(),vector.toString(),command.content().getBytes(java.nio.charset.StandardCharsets.UTF_8),command.documentVersion(),command.sourceUpdatedAt());elastic.put().uri("/"+command.indexVersion()+"/_doc/"+command.chunkId()).body(Map.of("documentId",command.documentId(),"chunkId",command.chunkId(),"title",command.title(),"content",command.content(),"category",command.category(),"visibility",command.visibility(),"documentVersion",command.documentVersion(),"sourceUpdatedAt",command.sourceUpdatedAt()==null?"":command.sourceUpdatedAt().toString())).retrieve().toBodilessEntity();}
 private static List<Raw>parse(Map<?,?>body){if(body==null)return List.of();var hits=(Map<?,?>)body.get("hits");if(hits==null)return List.of();var rows=(List<?>)hits.get("hits");if(rows==null)return List.of();var out=new ArrayList<Raw>();for(Object value:rows){var row=(Map<?,?>)value;var source=(Map<?,?>)row.get("_source");out.add(new Raw(Objects.toString(source.get("documentId")),Objects.toString(source.get("chunkId")),Objects.toString(source.get("title")),Objects.toString(source.get("content")),number(source.get("documentVersion")).longValue(),date(source.get("sourceUpdatedAt")),((Number)row.get("_score")).doubleValue(),0));}return out;}
 private static Number number(Object value){return value instanceof Number number?number:0;}private static OffsetDateTime date(Object value){try{String text=Objects.toString(value,"");return text.isBlank()?null:OffsetDateTime.parse(text);}catch(Exception ignored){return null;}}private static OffsetDateTime offset(Object value){if(value instanceof OffsetDateTime date)return date;if(value instanceof java.sql.Timestamp timestamp)return timestamp.toInstant().atOffset(ZoneOffset.UTC);return date(value);}private static String excerpt(String value){return value.length()<=300?value:value.substring(0,300);}
 private record Raw(String document,String chunk,String title,String content,long documentVersion,OffsetDateTime updatedAt,double lexical,double vector){String key(){return document+":"+chunk;}Raw withLexical(double score){return new Raw(document,chunk,title,content,documentVersion,updatedAt,score,vector);}Raw withVector(double score){return new Raw(document,chunk,title,content,documentVersion,updatedAt,lexical,score);}Raw merge(Raw other){return new Raw(document,chunk,title.isBlank()?other.title:title,content.isBlank()?other.content:content,documentVersion==0?other.documentVersion:documentVersion,updatedAt==null?other.updatedAt:updatedAt,lexical+other.lexical,vector+other.vector);}double finalScore(){return lexical+vector;}}
}
