server.port: ${YGH_PRODUCT_PORT:8084}
spring:
  application.name: ygh-product-service
  datasource:
    url: ${YGH_PRODUCT_DB_URL}
    username: ${YGH_PRODUCT_DB_APP_USERNAME:ygh_product_app}
    password: ${YGH_PRODUCT_DB_APP_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: ${YGH_PRODUCT_DB_URL}
    user: ${YGH_PRODUCT_DB_MIGRATION_USERNAME:ygh_product_migration}
    password: ${YGH_PRODUCT_DB_MIGRATION_PASSWORD}
    locations: classpath:db/migration
  cloud.nacos.discovery:
    server-addr: ${YGH_NACOS_SERVER_ADDR}
    username: ${YGH_NACOS_USERNAME}
    password: ${YGH_NACOS_PASSWORD}
    namespace: ${YGH_NACOS_NAMESPACE:ygh-dev}
    group: ${YGH_NACOS_DISCOVERY_GROUP:YGH_GROUP}
management.endpoints.web.exposure.include: health,info
