package com.yuegang.zhihui.knowledge.application;
import com.yuegang.zhihui.common.core.*;import com.yuegang.zhihui.knowledge.api.*;import java.io.*;import java.nio.charset.*;import java.nio.file.*;import java.security.*;import java.time.*;import java.util.*;import javax.sql.*;import org.apache.tika.*;import org.apache.tika.metadata.*;import org.apache.tika.parser.*;import org.apache.tika.sax.*;import org.springframework.jdbc.core.*;import org.springframework.jdbc.datasource.*;import org.springframework.transaction.support.*;import org.springframework.web.multipart.MultipartFile;
public final class KnowledgeDocumentService{
 private static final Set<String>ALLOWED=Set.of("application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain","text/markdown");private final JdbcTemplate jdbc;private final TransactionTemplate tx;private final Path root;private final Tika tika=new Tika();
 public KnowledgeDocumentService(DataSource d,String storage){jdbc=new JdbcTemplate(d);tx=new TransactionTemplate(new DataSourceTransactionManager(d));root=Path.of(storage).toAbsolutePath().normalize();try{Files.createDirectories(root);}catch(IOException e){throw new IllegalStateException(e);}}
 public KnowledgeDocumentView upload(long user,String title,String category,MultipartFile file){if(file.isEmpty()||file.getSize()>50L*1024*1024)throw invalid();String original=Optional.ofNullable(file.getOriginalFilename()).orElse("document");if(original.contains("/")||original.contains("\\")||original.indexOf('\0')>=0)throw invalid();long id=next();Path target=root.resolve(id+".bin").normalize();if(!target.startsWith(root))throw invalid();try{try(InputStream in=file.getInputStream()){Files.copy(in,target,StandardCopyOption.REPLACE_EXISTING);}String detected=detect(target,original);if(!ALLOWED.contains(detected))throw invalid();String sha=digest(target),text=parse(target);if(text.isBlank())throw invalid();return persist(user,title,category,file,original,id,target,detected,sha,text);}catch(IOException e){cleanup(target);throw new IllegalStateException("document IO failed",e);}catch(RuntimeException e){cleanup(target);throw e;}}
 private KnowledgeDocumentView persist(long user,String title,String category,MultipartFile file,String original,long id,Path target,String detected,String sha,String text){return tx.execute(s->{jdbc.update("INSERT INTO knowledge_document(id,title,category,file_name,media_type,size_bytes,sha256,storage_key,status,uploaded_by) VALUES(?,?,?,?,?,?,?,?, 'PENDING_REVIEW',?)",id,title.trim(),category,original,detected,file.getSize(),sha,target.getFileName().toString(),user);int index=0;for(String chunk:chunks(text))jdbc.update("INSERT INTO knowledge_chunk(id,document_id,chunk_index,content,token_count,content_sha256) VALUES(?,?,?,?,?,?)",next(),id,index++,chunk,Math.max(1,chunk.length()/2),digest(chunk));history(id,null,"UPLOADED",user,null);history(id,"UPLOADED","SECURITY_CHECKED",user,null);history(id,"SECURITY_CHECKED","PARSED",user,null);history(id,"PARSED","PENDING_REVIEW",user,null);return get(id);});}
 public KnowledgeDocumentView review(long reviewer,String document,ReviewKnowledgeRequest c){long id=id(document);String target=c.decision()==ReviewKnowledgeRequest.Decision.APPROVE?"PUBLISHED":"REJECTED";int n=jdbc.update("UPDATE knowledge_document SET status=?,reviewed_by=?,review_comment=?,published_at=CASE WHEN ?='PUBLISHED' THEN NOW(6) ELSE NULL END,version=version+1 WHERE id=? AND status='PENDING_REVIEW' AND version=?",target,reviewer,c.comment(),target,id,c.version());if(n!=1)throw new BusinessException(ErrorCode.BUSINESS_CONFLICT);jdbc.update("INSERT INTO knowledge_review(id,document_id,reviewer_id,decision,comment) VALUES(?,?,?,?,?)",next(),id,reviewer,c.decision().name(),c.comment());history(id,"PENDING_REVIEW",target,reviewer,c.comment());if("PUBLISHED".equals(target))jdbc.update("INSERT INTO knowledge_index_job(id,document_id,index_version,job_type,status) VALUES(?,?,?,'UPSERT','PENDING')",next(),id,"knowledge-v"+System.currentTimeMillis());return get(id);}
 public KnowledgeDocumentView get(long id){return jdbc.query("SELECT id,title,category,file_name,media_type,size_bytes,sha256,status,version,updated_at FROM knowledge_document WHERE id=?",r->{if(!r.next())throw new BusinessException(ErrorCode.RESOURCE_NOT_FOUND);return new KnowledgeDocumentView(Long.toString(r.getLong(1)),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getLong(6),r.getString(7),KnowledgeStatus.valueOf(r.getString(8)),r.getLong(9),r.getTimestamp(10).toLocalDateTime().atOffset(ZoneOffset.UTC));},id);}
 private String detect(Path p,String name)throws IOException{try(InputStream in=Files.newInputStream(p)){return tika.detect(in,name);}}private String parse(Path p){try(InputStream in=Files.newInputStream(p)){var h=new BodyContentHandler(5_000_000);new AutoDetectParser().parse(in,h,new Metadata(),new ParseContext());return h.toString().replace("\u0000","").trim();}catch(Exception e){throw invalid();}}
 private static List<String>chunks(String text){var out=new ArrayList<String>();for(int start=0;start<text.length();){int end=Math.min(text.length(),start+1200);String c=text.substring(start,end).trim();if(!c.isBlank())out.add(c);if(end==text.length())break;start=end-200;}return out;}private void history(long d,String f,String t,long u,String reason){jdbc.update("INSERT INTO knowledge_status_history(id,document_id,from_status,to_status,operator_id,reason) VALUES(?,?,?,?,?,?)",next(),d,f,t,u,reason);}private static void cleanup(Path p){try{Files.deleteIfExists(p);}catch(IOException ignored){}}private static String digest(Path p)throws IOException{try(InputStream in=Files.newInputStream(p)){MessageDigest d=MessageDigest.getInstance("SHA-256");in.transferTo(new DigestOutputStream(OutputStream.nullOutputStream(),d));return HexFormat.of().formatHex(d.digest());}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}private static String digest(String x){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(x.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private static long next(){return UUID.randomUUID().getMostSignificantBits()&Long.MAX_VALUE;}private static long id(String s){try{return Long.parseLong(s);}catch(Exception e){throw invalid();}}private static BusinessException invalid(){return new BusinessException(ErrorCode.VALIDATION_ERROR);}
}
