<script setup lang="ts">
import { computed, ref } from 'vue'
import { Search } from '@element-plus/icons-vue'
import ProductCard from '@/components/ProductCard.vue'
import { products } from '@/data/demo'
const keyword=ref('');const category=ref('全部');const sort=ref('综合排序')
const categories=['全部','岭南鲜果','港味手信','跨境零食','全球生鲜','岭南茶礼']
const filtered=computed(()=>[...products.filter(p=>(category.value==='全部'||p.categoryName===category.value)&&p.name.includes(keyword.value))].sort((a,b)=>sort.value==='价格从低到高'?Number(a.price)-Number(b.price):sort.value==='价格从高到低'?Number(b.price)-Number(a.price):0))
;</script>
<template><div class="page-shell"><div class="container"><div class="market-head"><div><span class="section-label">CROSS-BORDER MARKET</span><h1 class="page-title">跨境甄选商城</h1><p class="page-lead">公港生鲜、岭南特产、港澳手信与跨境零食。商品展示溯源信息，结算使用模拟钱包。</p></div><div class="search"><el-input v-model="keyword" size="large" placeholder="搜索商品、产地或规格" :prefix-icon="Search" clearable/></div></div><div class="filter-bar paper-card"><div><span>商品分类</span><button v-for="c in categories" :key="c" :class="{active:category===c}" @click="category=c">{{c}}</button></div><el-select v-model="sort" style="width:150px"><el-option v-for="s in ['综合排序','价格从低到高','价格从高到低']" :key="s" :label="s" :value="s"/></el-select></div><div class="result-line"><span>共找到 <b>{{filtered.length}}</b> 件商品</span><small>价格与库存以结算预览为准</small></div><div class="product-grid"><ProductCard v-for="p in filtered" :key="p.id" :product="p" @add="$router.push('/workspace/cart')"/></div><div v-if="!filtered.length" class="empty-state paper-card">没有符合当前条件的商品，请调整筛选条件。</div></div></div></template>
<style scoped>.market-head{display:flex;align-items:end;justify-content:space-between;margin-bottom:28px}.search{width:380px}.filter-bar{display:flex;align-items:center;justify-content:space-between;padding:18px 20px}.filter-bar>div{display:flex;align-items:center;gap:8px}.filter-bar span{margin-right:10px;color:var(--muted);font-size:13px}.filter-bar button{padding:7px 12px;border:0;border-radius:999px;background:transparent;color:#53635f;cursor:pointer}.filter-bar button.active{background:var(--jade);color:white}.result-line{display:flex;justify-content:space-between;margin:24px 2px 14px;color:var(--muted);font-size:13px}.result-line b{color:var(--cinnabar)}.product-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:18px}@media(max-width:900px){.market-head{align-items:start;flex-direction:column;gap:20px}.search{width:100%}.product-grid{grid-template-columns:repeat(2,1fr)}.filter-bar{align-items:start;flex-direction:column;gap:14px}.filter-bar>div{flex-wrap:wrap}}@media(max-width:550px){.product-grid{grid-template-columns:1fr}}</style>
